### ISSUE TITLE
wrong link in the readme.md?

### ISSUE THREAD

**Issue by DaDirnbocher** [KNHaw/ThunderbirdObsidianClipper#10]
The link to the addon site from thunderbird in the readme does not work for me.

this one works (for me): https://addons.thunderbird.net/en-US/thunderbird/addon/obsidianclipper/

**Comment by KNHaw** [comment]
Thank you for this catch! I cleaned up a bunch of comments in the code yesterday as part of pushing the v0.3.0 release and did a mass spelling change of "addon" to "add-on." Unfortunately, that hit the URLs in the README as well. If you happen to be in the Los Angeles, CA, USA area any time in the near future, let me know and I'll buy you a beverage of your choice!

Fixed with commit 18c5c76
