### ISSUE TITLE
Clipp only selected part of email

### ISSUE THREAD

**Issue by ferileho** [KNHaw/ThunderbirdObsidianClipper#22]
It would be great if only what I select by mouse in the mail could be sent to obsidian. Often the emails are full of previous communication. Right now I do this by deleting it in Obsidian after the fact. But these are often very long.. And marking the beginning of an email in Thunderbird is easier.

**Comment by KNHaw** [comment]
Thank you for reaching out on this issue. I already have this on the roadmap and it will be in the next release. Others have asked for this and it is actually a duplicate of [Issue 12](https://github.com/KNHaw/ThunderbirdObsidianClipper/issues/12) but I will leave this open so you can get updates instead of having to watch that issue.

The next release is coming soon, but I keep getting sidetracked on my day job. I will let you know when it comes out, though.

Thanks again for using ObsidianClipper!

**Comment by ferileho** [comment]
Thank you :)

**Comment by KNHaw** [comment]
For text selection, it took a little longer than expected, but I have fixed this in V0.4.0. Just select the desired text before clipping and only that part should be clipped. Please take a peek and let me know how you like it. I will close this issue out in the next few days unless you find issue with it.

@bepolymathe - For the TODO, what exactly do you have in mind? I'm unsure what this would look like.

**Comment by ferileho** [comment]
Text selection looks fine. Thank you :)

**Comment by KNHaw** [comment]
Thanks! I'm going to close this as fixed. Please let me know if anything else crops up. Thanks for using ObsidianClipper!
